### ISSUE TITLE
Error - npm run dev

### ISSUE THREAD

**Issue by herbetreis** [jesusantguerrero/sunday#115]
Estou com esse problema ao rodar o comando - npm run dev

```
  VITE v3.2.7  ready in 938 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose

  LARAVEL v9.51.0  plugin v0.5.4

  ➜  APP_URL: http://localhost
✘ [ERROR] Could not resolve "../index"

    node_modules/@formkit/auto-animate/vue/index.mjs:1:29:
      1 │ import { vAutoAnimate } from '../index';
        ╵                              ~~~~~~~~~~

/home/monday/sunday/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@formkit/auto-animate/vue/index.mjs:1:29: ERROR: Could not resolve "../index"
    at failureErrorWithLog (/home/monday/sunday/node_modules/esbuild/lib/main.js:1575:15)
    at /home/monday/sunday/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/home/monday/sunday/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/monday/sunday/node_modules/esbuild/lib/main.js:1031:7)
    at /home/monday/sunday/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/monday/sunday/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/monday/sunday/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/monday/sunday/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 29,
        file: 'node_modules/@formkit/auto-animate/vue/index.mjs',
        length: 10,
        line: 1,
        lineText: "import { vAutoAnimate } from '../index';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../index"'
    }
  ],
  warnings: []
}
```

Alguem sabe como contornar ?

Já rodei npm cache clean --force e npm install novamente, mas até agora nada.

**Comment by herbetreis** [comment]
Solved
